### PR TITLE
fix(tests): Fix flaky TestCloneGlobalLogger

### LINKED ISSUE #2761: [BUG] `LogSuite.TestCloneGlobalLogger` test fails frequently
**Describe the bug**
The test `LogSuite.TestCloneGlobalLogger` is flaky. The failure is always the same. It passes on retries.
The failure is as follows:
```
Log message dropped (buffer): {"189":189,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"190":190,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"191":191,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"192":192,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
 Error: Fluentbit connection error: Fluentbit connection problem: dial tcp 127.0.0.1:25000: connect: connection refused
{"level":"info","msg":"Test message","time":"2024-03-18T21:07:16.731944249Z"}
Log message dropped (buffer): {"193":193,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"194":194,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"195":195,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"196":196,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"197":197,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"198":198,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"199":199,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"200":200,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"201":201,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"202":202,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"203":203,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"204":204,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"205":205,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"206":206,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"207":207,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"208":208,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"209":209,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"210":210,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"211":211,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"212":212,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"213":213,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"214":214,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"215":215,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"216":216,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"217":217,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"218":218,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"219":219,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"220":220,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"221":221,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"222":222,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"223":223,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"224":224,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"225":225,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"226":226,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"227":227,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"228":228,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"229":229,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"230":230,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"231":231,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"232":232,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"233":233,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"234":234,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"235":235,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"236":236,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"237":237,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"238":238,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"239":239,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"240":240,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"241":241,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"242":242,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"243":243,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"244":244,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"245":245,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"246":246,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"247":247,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"248":248,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"249":249,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"250":250,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
{"251":251,"Level":"info","Message":"","Time":"0001-01-01T00:00:00Z"}
 Error: Fluentbit connection error: Fluentbit connection problem: dial tcp 127.0.0.1:25000: connect: connection refused

----------------------------------------------------------------------
FAIL: log_test.go:199: LogSuite.TestCloneGlobalLogger

log_test.go:244:
    c.Assert(len(capturedMessages), Equals, 1)
... obtained int = 0
... expected int = 1


----------------------------------------------------------------------
```

Example Run: https://github.com/kanisterio/kanister/actions/runs/8333523617/job/22805201911

### PR DESCRIPTION
**Pull request by e-sumin**
## Change Overview

Due to asynchronous nature of FluentbitHook test was not always passing. I've replaced it with synchronous hook, which guarantees the order of execution.

## Pull request type

Please check the type of change your PR introduces:
- [ ] :construction: Work in Progress
- [ ] :rainbow: Refactoring (no functional changes, no api changes)
- [ ] :hamster: Trivial/Minor
- [x] :bug: Bugfix
- [ ] :sunflower: Feature
- [ ] :world_map: Documentation
- [x] :robot: Test

## Issues 

- fixes #2761

## Test Plan

- [ ] :muscle: Manual
- [x] :zap: Unit test
- [ ] :green_heart: E2E

### CODE REVIEW

**Review by viveksinghggits — APPROVED** [review]

File: pkg/log/log_test.go [hunk 1]
```diff
@@ -241,11 +220,19 @@ func (s *LogSuite) TestCloneGlobalLogger(c *C) {
...
 
 	log.Println("Test message")
-	c.Assert(len(capturedMessages), Equals, 1)
-	c.Assert(capturedMessages[0].Message, Equals, "Test message")
+	c.Assert(len(hook.capturedMessages), Equals, 1)
+	c.Assert(hook.capturedMessages[0].Message, Equals, "Test message")
 }
 
-type testLogHook struct{}
+type testLogHook struct {
```
Comment (viveksinghggits) [inline pkg/log/log_test.go:227]: Nit: should we call it just `logHook`?
