### PR TITLE
Progress tracking actionset

### LINKED ISSUE #1576: [BUG] Kanister Controller cannot update Status on Kubernetes versions < v1.20
**Describe the bug**
Kanister Controller fails to add `Status` to ActionSets on Kubernetes Clusters of version < v1.20. 

**To Reproduce**
1. Build controller image from `master` branch
2. Install it on a cluster running K8s version 1.19 or lower
3. Create a Blueprint and an ActionSet to execute actions
4. Kanister controller fails to update the status
```
  Warning  Update Failed  5s    Kanister Controller  Could not update ActionSet: ActionSet.cr.kanister.io "hookbp-wmwr2" is invalid: status.progress.lastTransitionTime: Invalid value: "null": status.progress.lastTransitionTime in body must be of type string: "null"
```

**Expected behavior**
ActionSet should successfully run all the actions.

**Screenshots**
Example Blueprint:
```
apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata:
  name: hook-blueprint
  namespace: kanister
actions:
  post-export:
    kind: Namespace
    phases:
    - args:
        command:
        - /bin/sh
        - -c
        - |
          echo "This is a test phase"
        image: alpine:latest
        podOverride:
          serviceAccountName: myrelease-kanister-operator
      func: KubeTask
      name: hookPhase
```

Example ActionSet:
```
apiVersion: cr.kanister.io/v1alpha1
kind: ActionSet
metadata:
  generateName: hookbp-
  namespace: kanister
spec:
  actions:
  - name: post-export
    blueprint: hook-blueprint
    object:
      kind: Namespace
      name: default
      namespace: default
```

Describe ActionSet after creation:
```
Name:         hookbp-wmwr2
Namespace:    kanister
Labels:       <none>
Annotations:  <none>
API Version:  cr.kanister.io/v1alpha1
Kind:         ActionSet
Metadata:
  Creation Timestamp:  2022-07-29T22:46:40Z
  Generate Name:       hookbp-
  Generation:          1
  Managed Fields:
    API Version:  cr.kanister.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName:
      f:spec:
        .:
        f:actions:
    Manager:         kubectl-create
    Operation:       Update
    Time:            2022-07-29T22:46:40Z
  Resource Version:  57845
  Self Link:         /apis/cr.kanister.io/v1alpha1/namespaces/kanister/actionsets/hookbp-wmwr2
  UID:               71839463-5a08-4090-a9e7-d19724c018b6
Spec:
  Actions:
    Blueprint:  hook-blueprint
    Name:       post-export
    Object:
      Kind:       Namespace
      Name:       default
      Namespace:  default
Events:
  Type     Reason         Age   From                 Message
  ----     ------         ----  ----                 -------
  Warning  Update Failed  5s    Kanister Controller  Could not update ActionSet: ActionSet.cr.kanister.io "hookbp-wmwr2" is invalid: status.progress.lastTransitionTime: Invalid value: "null": status.progress.lastTransitionTime in body must be of type string: "null"
```

No issues on clusters with K8s v1.20 or above
```
Name:         hookbp-dzg8v
Namespace:    kanister
Labels:       <none>
Annotations:  <none>
API Version:  cr.kanister.io/v1alpha1
Kind:         ActionSet
Metadata:
  Creation Timestamp:  2022-07-29T20:19:07Z
  Generate Name:       hookbp-
  Generation:          9
  Managed Fields:
    API Version:  cr.kanister.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName:
      f:spec:
    Manager:      kubectl-create
    Operation:    Update
    Time:         2022-07-29T20:19:07Z
    API Version:  cr.kanister.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:actions:
      f:status:
        .:
        f:actions:
        f:error:
          .:
          f:message:
        f:progress:
          .:
          f:lastTransitionTime:
          f:percentCompleted:
        f:state:
    Manager:         controller
    Operation:       Update
    Time:            2022-07-29T20:19:09Z
  Resource Version:  12830367
  UID:               521f4c46-4fda-4ace-9f9b-523aaec33988
Spec:
  Actions:
    Blueprint:  hook-blueprint
    Name:       post-export
    Object:
      API Version:
      Group:
      Kind:             Namespace
      Name:             default
      Namespace:        default
      Resource:
    Preferred Version:
Status:
  Actions:
    Blueprint:  hook-blueprint
    Defer Phase:
      Name:
      State:
    Name:     post-export
    Object:
      API Version:
      Group:
      Kind:         Namespace
      Name:         default
      Namespace:    default
      Resource:
    Phases:
      Name:   hookPhase
      State:  complete
  Error:
    Message:
  Progress:
    Last Transition Time:  2022-07-29T20:19:15Z
    Percent Completed:     100.00
  State:                   complete
Events:
  Type    Reason           Age    From                 Message
  ----    ------           ----   ----                 -------
  Normal  Started Action   3m52s  Kanister Controller  Executing action post-export
  Normal  Started Phase    3m52s  Kanister Controller  Executing phase hookPhase
  Normal  Ended Phase      3m45s  Kanister Controller  Completed phase hookPhase
  Normal  Update Complete  3m45s  Kanister Controller  Updated ActionSet 'hookbp-dzg8v' Status->complete
  Normal  Update Complete  3m44s  Kanister Controller  Updated ActionSet 'hookbp-dzg8v' Status->complete
```

**Environment**
Kubernetes Version/Provider: 1.18.2/AWS (deployed using KOPS)
Storage Provider: EFS
Cluster Size (#nodes): 3
Data Size: N/A

### PR DESCRIPTION
**Pull request by viveksinghggits**
## Change Overview

Re-opens https://github.com/kanisterio/kanister/pull/1487, with https://github.com/kanisterio/kanister/issues/1576 fix.

## Pull request type

Please check the type of change your PR introduces:
- [ ] :construction: Work in Progress
- [ ] :rainbow: Refactoring (no functional changes, no api changes)
- [ ] :hamster: Trivial/Minor
- [x] :bug: Bugfix
- [ ] :sunflower: Feature
- [ ] :world_map: Documentation
- [ ] :robot: Test

## Issues 

- fixes #1576 

## Test Plan

- [x] :muscle: Manual
- [x] :zap: Unit test

```
/kanister/pkg/progress (progress-tracking-actionset*) » go test                       
OK: 6 passed
PASS
ok  	github.com/kanisterio/kanister/pkg/progress	0.026s
```

Install Kanister on k8s version 1.19 and 1.21 to check if we are backup and restore an application.

```
kctx: kind-kind
~/work/opensource/kanister/pkg/progress (progress-tracking-actionset*) » k version 
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

kctx: kind-kind
~/work/opensource/kanister/pkg/progress (progress-tracking-actionset*) » k get actionsets.cr.kanister.io -n kanister
NAME                         PROGRESS   LAST TRANSITION TIME   STATE
backup-22dtd                 100.00     2022-08-05T14:16:49Z   complete
backup-bl5w2                 100.00     2022-08-05T14:16:33Z   complete
restore-backup-22dtd-stq9j   100.00     2022-08-05T14:31:19Z   complete
```

```
kctx: kind-kind
~/work/opensource/kanister/examples/mysql (progress-tracking-actionset*) » k version 
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.16", GitCommit:"e37e4ab4cc8dcda84f1344dda47a97bb1927d074", GitTreeState:"clean", BuildDate:"2022-05-19T20:23:31Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.19) exceeds the supported minor version skew of +/-1

kctx: kind-kind
~/work/opensource/kanister/examples/mysql (progress-tracking-actionset*) » k get actionsets.cr.kanister.io -n kanister 
NAME                         PROGRESS   LAST TRANSITION TIME   STATE
backup-jpldg                 100.00     2022-08-05T14:39:43Z   complete
restore-backup-jpldg-vjlvp   100.00     2022-08-05T14:40:04Z   complete

```

### CODE REVIEW

File: pkg/progress/action_single_phase_test.go [hunk 1]
```diff
@@ -0,0 +1,197 @@
...
+	c.Assert(err, IsNil)
+
+	updateErr := updateActionsProgress(context.Background(), clientset, updated, phaseWeights, totalWeight, now)
+	c.Assert(updateErr, IsNil)
+
+	// retrieve the latest actionSet resource to confirm its progress data
+	actual, err := clientset.CrV1alpha1().ActionSets(actionSet.GetNamespace()).Get(context.Background(), updated.GetName(), metav1.GetOptions{})
+	c.Assert(err, IsNil, Commentf("test case #: %d", testCaseID))
+	c.Assert(actual.Status.Progress.PercentCompleted, Equals, expectedPercentCompleted, Commentf("test case #: %d", testCaseID))
+	c.Assert(actual.Status.Progress.LastTransitionTime.Time, Equals, now, Commentf("test case #: %d", testCaseID))
```
Comment (pavannd1) [inline pkg/progress/action_single_phase_test.go:196]:
```suggestion
	c.Assert(actual.Status.Progress.LastTransitionTime, NotNil)
	c.Assert(actual.Status.Progress.LastTransitionTime.Time, Equals, now, Commentf("test case #: %d", testCaseID))
```
We should probably add a non-nil check here

File: pkg/apis/cr/v1alpha1/types.go [hunk 2]
```diff
@@ -131,6 +132,16 @@ type ActionStatus struct {
...
 }
 
+// ActionProgress provides information on the progress of an action.
+type ActionProgress struct {
+	// PercentCompleted is computed by assessing the number of completed phases
+	// against the the total number of phases.
+	PercentCompleted string `json:"percentCompleted"`
+	// LastTransitionTime represents the last date time when the progress status
+	// was received.
+	LastTransitionTime *metav1.Time `json:"lastTransitionTime,omitempty"`
```
Comment (pavannd1) [inline pkg/apis/cr/v1alpha1/types.go:142]: As discussed offline, looks like the only difference between my attempts to fix and your PR is the `omitempty` 💡 🤔 
Should we add it to `PercentCompleted` also?

File: pkg/progress/action.go [hunk 3]
```diff
@@ -0,0 +1,215 @@
...
+	"time"
+
+	crv1alpha1 "github.com/kanisterio/kanister/pkg/apis/cr/v1alpha1"
+	"github.com/kanisterio/kanister/pkg/client/clientset/versioned"
+	"github.com/kanisterio/kanister/pkg/field"
+	fn "github.com/kanisterio/kanister/pkg/function"
+	"github.com/kanisterio/kanister/pkg/log"
+	"github.com/kanisterio/kanister/pkg/reconcile"
+	"github.com/kanisterio/kanister/pkg/validate"
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
```
Comment (PrasadG193) [inline pkg/progress/action.go:16]: Third-party pkg imports should be in separate group

File: pkg/progress/action.go [hunk 4]
```diff
@@ -0,0 +1,215 @@
...
+		"actionSet": actionSet.GetName(),
+		"namespace": actionSet.GetNamespace(),
+		"progress":  progressPercent,
+	}
+	log.Debug().Print("updating action progress", fields)
+
+	return updateActionSet(ctx, client, actionSet, progressPercent, now)
+}
+
+func weight(phase *crv1alpha1.BlueprintPhase) float64 {
```
Comment (PrasadG193) [inline pkg/progress/action.go:173]: [nit] ideally function name should start with a verb. e.g `calculateWeight` or `getWeight`

File: pkg/progress/action.go [hunk 5]
```diff
@@ -0,0 +1,215 @@
...
+	if longRunning(phase) {
+		return weightHeavy
+	}
+	return weightNormal
+}
+
+func longRunning(phase *crv1alpha1.BlueprintPhase) bool {
```
Comment (PrasadG193) [inline pkg/progress/action.go:180]: [nit] since the function returns bool - we can rename it to something - `containsLongRunningFunc`

File: pkg/progress/action.go [hunk 6]
```diff
@@ -0,0 +1,215 @@
...
+	}
+
+	if err := reconcile.ActionSet(ctx, client.CrV1alpha1(), actionSet.GetNamespace(), actionSet.GetName(), updateFunc); err != nil {
+		return err
+	}
+
+	return nil
+}
+
+func completedOrFailed(actionSet *crv1alpha1.ActionSet) bool {
```
Comment (PrasadG193) [inline pkg/progress/action.go:212]: [nit] Since the func returns bool, we can rename this to something like - `isCompletedOrFailed`

File: pkg/progress/action.go [hunk 7]
```diff
@@ -0,0 +1,215 @@
...
+				continue
+			}
+
+			if err := updateActionsProgress(ctx, client, actionSet, phaseWeights, totalWeight, time.Now()); err != nil {
+				fields := field.M{
+					"actionSet":      actionSet.Name,
+					"nextUpdateTime": time.Now().Add(pollDuration),
+				}
+				log.Error().WithError(err).Print("failed to update phase progress", fields)
+				continue
```
Comment (PrasadG193) [inline pkg/progress/action.go:82]: This may run into an infinite loop if the client fails to update action progress every iteration. Instead of continue, should we return error?

File: pkg/progress/action.go [hunk 8]
```diff
@@ -0,0 +1,215 @@
...
+	if progressPercent == progressPercentNotStarted {
+		progressPercent = progressPercentStarted
+	}
+
+	fields := field.M{
+		"actionSet": actionSet.GetName(),
+		"namespace": actionSet.GetNamespace(),
+		"progress":  progressPercent,
+	}
+	log.Debug().Print("updating action progress", fields)
```
Comment (PrasadG193) [inline pkg/progress/action.go:168]: We should also add actionset name (and may be phase name as well) to the logs so that we can differentiate between logs in case of multiple statements

File: pkg/progress/action.go [hunk 9]
```diff
@@ -0,0 +1,215 @@
...
+		actionSet.Status.Progress.PercentCompleted = progressPercent
+		actionSet.Status.Progress.LastTransitionTime = &metav1Time
+		return nil
+	}
+
+	if err := reconcile.ActionSet(ctx, client.CrV1alpha1(), actionSet.GetNamespace(), actionSet.GetName(), updateFunc); err != nil {
+		return err
+	}
+
+	return nil
```
Comment (PrasadG193) [inline pkg/progress/action.go:209]:
```suggestion
	return reconcile.ActionSet(ctx, client.CrV1alpha1(), actionSet.GetNamespace(), actionSet.GetName(), updateFunc)
```
error check can be skipped

File: pkg/apis/cr/v1alpha1/types.go [hunk 10]
```diff
@@ -131,6 +132,16 @@ type ActionStatus struct {
 	DeferPhase Phase `json:"deferPhase,omitempty"`
 }
 
+// ActionProgress provides information on the progress of an action.
+type ActionProgress struct {
```
Comment (PrasadG193) [inline pkg/apis/cr/v1alpha1/types.go:136]: should we also add the name of the current phase in progress?

Comment (ihcsim) [reply pkg/apis/cr/v1alpha1/types.go:136]: phase progress is planned for the next iteration. at this level, we just want to communicate the overall progress without bloating the API spec.

File: pkg/progress/action.go (hunk 7 above)
Comment (ihcsim) [reply pkg/progress/action.go:82]: The idea here is to ignore intermediate, flakey errors, due to e.g., API server or client-go throttling. The final progress should always be calculated based on the actionset status. If the actionset status completed, progress should always be 100% despite of intermediate errors.

**Review by pavannd1 — APPROVED** [review]
I believe most of the changes in this PR are a part of the revert and were previously approved. My approval is purely focused on the bug fix here. We can follow up on the other review comments in a separate PR.

**Review by ihcsim — APPROVED** [review]
@viveksinghggits Thanks for working on this :+1:. Since the previous PR has been reviewed quite a bit, we should keep changes to this PR to the minimal, unless more bugs are found. If possible, I want to avoid another round of review churns - that last PR took a month (or more?)  to merge.

I suggest other important non-bug review items be added to a new GH issue, which we may or may not address when we start the phase progress work.

We should start finding ways to surface these kind of errors sooner in the dev cycle. Reverting PRs is costly and inefficient as they create churns and re-works.
