### PR TITLE
Fixed issue-1176: Reduce resource requests while installing minio

### LINKED ISSUE #1176: [BUG] make install-minio fails sometimes because of resource issues
**Describe the bug**
To test the integrations tests when as a prerequisite when we run `make install-minio` it sometimes fails because of the resource requirement of minio deployment.
It, I think, by default requests 5G which might not be available on some of the clusters. We should try to install minio with lesser resource request, if their helm chart provides this.

**To Reproduce**

Run `make install-minio` it fails sometimes.

**Expected behavior**
Minio should be installed successfully.

### PR DESCRIPTION
**Pull request by shahpratikr**
Signed-off-by: Pratik Shah <pratik@infracloud.io>

## Change Overview

- Set resources.requests.memory to 2Gi

## Pull request type

Please check the type of change your PR introduces:
- [ ] :construction: Work in Progress
- [ ] :rainbow: Refactoring (no functional changes, no api changes)
- [x] :hamster: Trivial/Minor
- [x] :bug: Bugfix
- [ ] :sunflower: Feature
- [ ] :world_map: Documentation
- [ ] :robot: Test

## Issues 

- fixes #1176 

## Test Plan

- [x] :muscle: Manual
- [ ] :zap: Unit test
- [ ] :green_heart: E2E

Ran integration tests locally `make install-minio; make integration-tests`

### CODE REVIEW

File: build/minio.sh [hunk 1]
```diff
@@ -72,7 +81,11 @@ EOM
 case "${1}" in
         # Alphabetically sorted
         install_minio)
-            time -p install_minio
+            if [[ ${#@} -eq 2 ]]; then
+                time -p install_minio ${2}
+            else
+                time -p install_minio
+            fi
```
Comment (viveksinghggits) [inline build/minio.sh:88]: Instead of calling `install_minio` twice here. Let's just call install_minio from here will all the passed arguments and then handle things in the definition of install_minio.

File: build/minio.sh [hunk 2]
```diff
@@ -46,6 +48,7 @@ install_minio ()
     echo AWS_ACCESS_KEY_ID="AKIAIOSFODNN7EXAMPLE"
     echo AWS_SECRET_ACCESS_KEY="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
     echo AWS_REGION="us-west-2"
+    echo S3_BUCKET_NAME="tests.kanister.io"
```
Comment (viveksinghggits) [inline build/minio.sh:51]: we don't need this change right?

Comment (shahpratikr) [reply build/minio.sh]: reverted

File: build/minio.sh (hunk 1 above)
Comment (shahpratikr) [reply build/minio.sh]: fixed

File: build/minio.sh [hunk 3]
```diff
@@ -37,6 +38,7 @@ install_minio ()
     --set environment.MINIO_SSE_AUTO_ENCRYPTION=on \
     --set environment.MINIO_SSE_MASTER_KEY=my-minio-key:feb5bb6c5cf851e21dbc0376ca81012a9edc4ca0ceeb9df5064ccba2991ae9de \
     --set accessKey="AKIAIOSFODNN7EXAMPLE",secretKey="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" \
+    --set resources.requests.memory=2Gi,persistence.size=${pvc_size} \
```
Comment (PrasadG193) [inline build/minio.sh:41]: Do we really need 2Gi memory requests? Can you check if 100Mi/200Mi would be enough?

File: build/minio.sh [hunk 4]
```diff
@@ -23,6 +23,7 @@ MINIO_CHART_VERSION="8.0.0"
 
 install_minio ()
 {
+    local pvc_size=${2:-"2Gi"}
```
Comment (PrasadG193) [inline build/minio.sh:26]: 2Gi storage for a test seems way more than required. Can we run tests with a lesser minio storage capacity?

**Comment by PrasadG193** [comment]
In fact, for tests, we don't even need persistent minio storage.

File: build/minio.sh (hunk 3 above)
Comment (viveksinghggits) [reply build/minio.sh:41]: we don't even have to change the persistence size. That was not the problem. 
We were just supposed to handle the resource that minio needs. So memory basically.

Comment (shahpratikr) [reply build/minio.sh:41]: added pvc change because of [this](https://github.com/kanisterio/kanister/issues/1176#issuecomment-1122817635) comment.

Comment (shahpratikr) [reply build/minio.sh]: reverted pvc change

File: build/minio.sh (hunk 4 above)
Comment (shahpratikr) [reply build/minio.sh]: reverted

**Review by viveksinghggits — APPROVED** [review]

**Review by PrasadG193 — APPROVED** [review]
