### PR TITLE
DEVOPS-7803 restore log stream

### LINKED ISSUE #1622: [BUG] Problem with long running phase
**Describe the bug**

When phase takes about 6 hours, the operator (0.81.0) does not set the `snapshot_id` in the `ActionSet` despite using kando for this purpose.

**To Reproduce**

Blueprint:
```
  backup:
    kind: Deployment
    outputArtifacts:
      mysql_backup:
        keyValue:
          snapshot_id: '{{ .Phases.backupMySQL.Output.snapshot_id }}'
    phases:
      - args:
          command:
            - bash
            - '-o'
            - errexit
            - '-o'
            - pipefail
            - '-o'
            - errtrace
            - '-c'
            - |
              sleep 20000
              kando output snapshot_id 6c1b0940
          namespace: mysql
        func: KubeTask
        name: backupMySQL
```

ActionSet describe:
```
Name:         backup-mysql-2022-09-04-00-00
Namespace:    mysql
Labels:       <none>
Annotations:  <none>
API Version:  cr.kanister.io/v1alpha1
Kind:         ActionSet

(...)

Spec:
  Actions:
    Blueprint:  service-backups-mysql
    Name:       backup
    Object:
      API Version:      
      Group:            
      Kind:             Deployment
      Name:             platform-operator-mysql
      Namespace:        mysql
      Resource:         
    Preferred Version:  
Status:
  Actions:
    Artifacts:
      mysql_backup:
        Key Value:
          snapshot_id:  {{ .Phases.backupMySQL.Output.snapshot_id }}
    Blueprint:          service-backups-mysql
    Name:               backup
    Object:
      API Version:  
      Group:        
      Kind:         Deployment
      Name:         platform-operator-mysql
      Namespace:    mysql
      Resource:     
    Phases:
      Name:   backupMySQL
      State:  complete
  Error:
    Message:  Failed to render template: "snapshot_id" not found
  State:      failed
Events:       <none>
```

Operator logs:
```
2022-09-04T00:00:03.815136760Z {"ActionSet":"backup-mysql-2022-09-04-00-00","File":"pkg/controller/controller.go","Function":"github.com/kanisterio/kanister/pkg/controller.(*Controller).logAndSuccessEvent","Line":643,"hostname":"service-operator-kanister-764b48bbb-2m6cx","level":"info","msg":"Executing action backup","time":"2022-09-04T00:00:03.813944563Z"}
2022-09-04T00:00:03.977164547Z {"ActionSet":"backup-mysql-2022-09-04-00-00","File":"pkg/controller/controller.go","Function":"github.com/kanisterio/kanister/pkg/controller.(*Controller).handleActionSet","Line":396,"NewActionSetName":"backup-mysql-2022-09-04-00-00","hostname":"service-operator-kanister-764b48bbb-2m6cx","level":"info","msg":"Created actionset and started executing actions","time":"2022-09-04T00:00:03.974906861Z"}
2022-09-04T00:00:03.977216450Z {"ActionSet":"backup-mysql-2022-09-04-00-00","File":"pkg/controller/controller.go","Function":"github.com/kanisterio/kanister/pkg/controller.(*Controller).logAndSuccessEvent","Line":643,"Phase":"backupMySQL","hostname":"service-operator-kanister-764b48bbb-2m6cx","level":"info","msg":"Executing phase backupMySQL","time":"2022-09-04T00:00:03.975206032Z"}
2022-09-04T00:00:03.981810552Z {"ActionSet":"backup-mysql-2022-09-04-00-00","File":"pkg/controller/controller.go","Function":"github.com/kanisterio/kanister/pkg/controller.(*Controller).onUpdateActionSet","Line":238,"Status":"pending","hostname":"service-operator-kanister-764b48bbb-2m6cx","level":"info","msg":"Updated ActionSet","time":"2022-09-04T00:00:03.97779321Z"}
2022-09-04T00:00:03.981852784Z {"ActionSet":"backup-mysql-2022-09-04-00-00","File":"pkg/controller/controller.go","Function":"github.com/kanisterio/kanister/pkg/controller.(*Controller).onUpdateActionSet","Line":245,"Phase":"backupMySQL-\u003epending","Status":"running","hostname":"service-operator-kanister-764b48bbb-2m6cx","level":"info","msg":"Updated ActionSet","time":"2022-09-04T00:00:03.977920245Z"}
2022-09-04T05:33:30.055810444Z {"ActionSet":"backup-mysql-2022-09-04-00-00","File":"pkg/controller/controller.go","Function":"github.com/kanisterio/kanister/pkg/controller.(*Controller).logAndSuccessEvent","Line":643,"Phase":"backupMySQL","hostname":"service-operator-kanister-764b48bbb-2m6cx","level":"info","msg":"Completed phase backupMySQL","time":"2022-09-04T05:33:30.055486706Z"}
2022-09-04T05:33:30.072749945Z {"ActionSet":"backup-mysql-2022-09-04-00-00","File":"pkg/controller/controller.go","Function":"github.com/kanisterio/kanister/pkg/controller.(*Controller).onUpdateActionSet","Line":238,"Status":"failed","hostname":"service-operator-kanister-764b48bbb-2m6cx","level":"info","msg":"Updated ActionSet","time":"2022-09-04T05:33:30.072434534Z"}
2022-09-04T05:33:30.072820757Z {"ActionSet":"backup-mysql-2022-09-04-00-00","File":"pkg/controller/controller.go","Function":"github.com/kanisterio/kanister/pkg/controller.(*Controller).logAndErrorEvent","Line":626,"Phase":"backupMySQL","error":"Failed to render template: \"snapshot_id\" not found","hostname":"service-operator-kanister-764b48bbb-2m6cx","level":"info","msg":"Failed to render output artifacts","time":"2022-09-04T05:33:30.072552115Z"}
```

**Expected behavior**
An artifact has been set, key: `snapshot_id` value: `6c1b0940`

**Environment**
Kubernetes Version/Provider: 1.22
Cluster Size (#nodes): 1

**Additional context**
Instead of `sleep 20000` in my blueprint there is a mysqldump which output is streamed to the restic repository. Due to the size of the database and limited bandwidth, this is how long it takes. In the case of a shorter time, I was unable to reproduce the problem.

### PR DESCRIPTION
**Pull request by DCkQ6**
## Change Overview

Unfortunately, there is a hardcoded timeout in the kubelet server. If we want to support long-lasting phases, we need to work around it.

This PR introduces re-establishing the log stream connection while the pod is still running.

## Pull request type

Please check the type of change your PR introduces:
- [ ] :construction: Work in Progress
- [ ] :rainbow: Refactoring (no functional changes, no api changes)
- [ ] :hamster: Trivial/Minor
- [x] :bug: Bugfix
- [ ] :sunflower: Feature
- [ ] :world_map: Documentation
- [ ] :robot: Test

## Issues 

- fixes #1622 

## Test Plan

I created a phase executing function `KubeTask`, with a long-lasting command (sleep). I ensured that the logs were read until the end of its execution and that the output was properly gathered.

- [x] :muscle: Manual
- [ ] :zap: Unit test
- [ ] :green_heart: E2E

### CODE REVIEW

File: pkg/kube/pod_controller.go [hunk 1]
```diff
@@ -230,7 +230,66 @@ func (p *podController) StreamPodLogs(ctx context.Context) (io.ReadCloser, error
...
+	namespace     string
+	podName       string
+	containerName string
+	reader        io.ReadCloser
+	lastReadTime  metav1.Time
+}
+
+func (s *restoreLogStreamReader) Read(p []byte) (n int, err error) {
+	n, err = s.reader.Read(p)
+	defer func() { s.lastReadTime = metav1.Now() }()
```
Comment (hairyhum) [inline pkg/kube/pod_controller.go:266]: This looks like we take the timestamp after the stream close. My main concern in https://github.com/kanisterio/kanister/pull/2903#discussion_r1616349780 was that if there was a log at the time of the stream close we might lose some records. 
Did you have a way to reproduce the failure so we can have at least empirical proof that this approach works?

File: pkg/kube/pod_controller.go [hunk 2]
```diff
@@ -230,7 +230,66 @@ func (p *podController) StreamPodLogs(ctx context.Context) (io.ReadCloser, error
...
+		err = s.reader.Close()
+		if err != nil {
+			return 0, err
+		}
+		s.reader, err = StreamPodLogs(s.ctx, s.cli, s.namespace, s.podName, s.containerName, &s.lastReadTime)
+		if err != nil {
+			return 0, err
+		}
+
+		return s.reader.Read(p)
```
Comment (hairyhum) [inline pkg/kube/pod_controller.go:286]: This looks like a stream read is only repeated once. Should we assume that it can happen multiple times and use a loop instead? I don't really see a reason why it wouldn't happen multiple times, am I missing something?

**Review by hairyhum — COMMENTED** [review]
This approach is better, but can we have some automated test to prove that we don't lose logs?

File: pkg/kube/pod_controller.go (hunk 2 above)
Comment (DCkQ6) [reply pkg/kube/pod_controller.go:286]: It's very unlikely that the new stream will return io.EOF, and even if it does, we should not assume it is for the same reason that we try to fix in this PR. A safer option will be to resume the connection only once after a successful read.

File: pkg/kube/pod_controller.go (hunk 1 above)
Comment (DCkQ6) [reply pkg/kube/pod_controller.go:266]: Yes, there is a way to reproduce it, and I did it. Unfortunately, each test takes 4 hours as I just run an action from a blueprint that uses a long `sleep` and `echo`.

This approach in manual tests always resulted in a duplicated last line of the log, which was independent of the frequency of the log. The last line was repeated even if it was the only line since 4 hours.

File: pkg/kube/pod_controller.go (hunk 2 above)
Comment (hairyhum) [reply pkg/kube/pod_controller.go:286]: Ok. Fair enough

File: pkg/kube/pod_controller.go (hunk 1 above)
Comment (DCkQ6) [reply pkg/kube/pod_controller.go:266]: Deduplication would be quite an overhead for what we are trying to achieve. This problem manifests only after 4 hours, and a single duplicated line for tasks that take over 4 hours, in my opinion, doesn't justify the need to add deduplication logic. This logic would require storing the last read line in memory and comparing it after reconnecting. Additionally, we should not assume that our users' logs distinguish between lines, which would complicate such a simple comparison.

Therefore, in my opinion, we should accept this single duplicated line that occurs on rare occasions.

**Comment by maksym-herbert** [comment]
@e-sumin, any updates on the review?

**Comment by hairyhum** [comment]
To follow up: it's possible to read a full log after operation finished to get a reliable view of the outputs.

**Comment by hairyhum** [comment]
TODO: add test verifying that log reading is recovered after interruption

**Review by hairyhum — APPROVED** [review]
